from enum import Enum


class SQLContext(Enum):
    EMPTY = "EMPTY"
    SINGLE_TOKEN = "SINGLE_TOKEN"
    DOT_COMPLETION = "DOT_COMPLETION"
    SELECT_LIST = "SELECT_LIST"
    FROM_CLAUSE = "FROM_CLAUSE"
    JOIN_CLAUSE = "JOIN_CLAUSE"
    JOIN_ON = "JOIN_ON"
    WHERE_CLAUSE = "WHERE_CLAUSE"
    ORDER_BY_CLAUSE = "ORDER_BY"
    GROUP_BY_CLAUSE = "GROUP_BY"
    HAVING_CLAUSE = "HAVING"
    LIMIT_OFFSET_CLAUSE = "LIMIT_OFFSET"
    UNKNOWN = "UNKNOWN"
