from enum import Enum


class SQLContext(Enum):
    EMPTY = "EMPTY"
    SINGLE_TOKEN = "SINGLE_TOKEN"
    DOT_COMPLETION = "DOT_COMPLETION"
    SELECT_LIST = "SELECT_LIST"
    FROM_CLAUSE = "FROM_CLAUSE"
    JOIN_CLAUSE = "JOIN_CLAUSE"
    JOIN_AFTER_TABLE = "JOIN_AFTER_TABLE"
    JOIN_ON = "JOIN_ON"
    JOIN_ON_AFTER_OPERATOR = "JOIN_ON_AFTER_OPERATOR"
    JOIN_ON_AFTER_EXPRESSION = "JOIN_ON_AFTER_EXPRESSION"
    WHERE_CLAUSE = "WHERE_CLAUSE"
    WHERE_AFTER_OPERATOR = "WHERE_AFTER_OPERATOR"
    WHERE_AFTER_EXPRESSION = "WHERE_AFTER_EXPRESSION"
    ORDER_BY_CLAUSE = "ORDER_BY"
    ORDER_BY_AFTER_COLUMN = "ORDER_BY_AFTER_COLUMN"
    GROUP_BY_CLAUSE = "GROUP_BY"
    HAVING_CLAUSE = "HAVING"
    HAVING_AFTER_OPERATOR = "HAVING_AFTER_OPERATOR"
    HAVING_AFTER_EXPRESSION = "HAVING_AFTER_EXPRESSION"
    WINDOW_OVER = "WINDOW_OVER"
    LIMIT_OFFSET_CLAUSE = "LIMIT_OFFSET"
    AFTER_LIMIT_NUMBER = "AFTER_LIMIT_NUMBER"

    # INSERT contexts
    INSERT_INTO = "INSERT_INTO"
    INSERT_COLUMNS = "INSERT_COLUMNS"
    INSERT_VALUES = "INSERT_VALUES"
    INSERT_VALUE_EXPRESSIONS = "INSERT_VALUE_EXPRESSIONS"
    INSERT_COMPLETE = "INSERT_COMPLETE"
    INSERT_POST_VALUES = "INSERT_POST_VALUES"
    INSERT_STRING_LITERAL = "INSERT_STRING_LITERAL"

    # UPDATE contexts
    UPDATE_TABLE = "UPDATE_TABLE"
    UPDATE_SET_CLAUSE = "UPDATE_SET_CLAUSE"
    UPDATE_SET_COLUMNS = "UPDATE_SET_COLUMNS"
    UPDATE_SET_EXPRESSIONS = "UPDATE_SET_EXPRESSIONS"
    UPDATE_WHERE_CLAUSE = "UPDATE_WHERE_CLAUSE"
    UPDATE_WHERE_CONDITIONS = "UPDATE_WHERE_CONDITIONS"
    UPDATE_WHERE_OPERATORS = "UPDATE_WHERE_OPERATORS"
    UPDATE_JOIN_ON = "UPDATE_JOIN_ON"
    UPDATE_STRING_LITERAL = "UPDATE_STRING_LITERAL"
    UPDATE_WHERE_STRING_LITERAL = "UPDATE_WHERE_STRING_LITERAL"

    # DELETE contexts
    DELETE_FROM = "DELETE_FROM"
    DELETE_WHERE_CLAUSE = "DELETE_WHERE_CLAUSE"
    DELETE_WHERE_CONDITIONS = "DELETE_WHERE_CONDITIONS"
    DELETE_WHERE_OPERATORS = "DELETE_WHERE_OPERATORS"
    DELETE_WHERE_EXPRESSIONS = "DELETE_WHERE_EXPRESSIONS"
    DELETE_JOIN_ON = "DELETE_JOIN_ON"
    DELETE_USING = "DELETE_USING"
    DELETE_SUBQUERY = "DELETE_SUBQUERY"
    DELETE_WHERE_STRING_LITERAL = "DELETE_WHERE_STRING_LITERAL"

    # SELECT WHERE string literal
    WHERE_STRING_LITERAL = "WHERE_STRING_LITERAL"

    UNKNOWN = "UNKNOWN"
