from enum import Enum


class SQLContext(Enum):
    EMPTY = "EMPTY"
    SINGLE_TOKEN = "SINGLE_TOKEN"
    DOT_COMPLETION = "DOT_COMPLETION"
    SELECT_LIST = "SELECT_LIST"
    FROM_CLAUSE = "FROM_CLAUSE"
    JOIN_CLAUSE = "JOIN_CLAUSE"
    JOIN_AFTER_TABLE = "JOIN_AFTER_TABLE"
    JOIN_ON = "JOIN_ON"
    JOIN_ON_AFTER_OPERATOR = "JOIN_ON_AFTER_OPERATOR"
    JOIN_ON_AFTER_EXPRESSION = "JOIN_ON_AFTER_EXPRESSION"
    WHERE_CLAUSE = "WHERE_CLAUSE"
    WHERE_AFTER_OPERATOR = "WHERE_AFTER_OPERATOR"
    WHERE_AFTER_EXPRESSION = "WHERE_AFTER_EXPRESSION"
    ORDER_BY_CLAUSE = "ORDER_BY"
    GROUP_BY_CLAUSE = "GROUP_BY"
    HAVING_CLAUSE = "HAVING"
    HAVING_AFTER_OPERATOR = "HAVING_AFTER_OPERATOR"
    HAVING_AFTER_EXPRESSION = "HAVING_AFTER_EXPRESSION"
    LIMIT_OFFSET_CLAUSE = "LIMIT_OFFSET"
    UNKNOWN = "UNKNOWN"
